default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://dwqawyqa:hTqF1-qiKe9d6AtZvW_0jcuDHrYZMejs@ella.db.elephantsql.com/dwqawyqa
  # username: postgres
  # password: postgresql

production:
  <<: *default
  url: postgres://dwqawyqa:hTqF1-qiKe9d6AtZvW_0jcuDHrYZMejs@ella.db.elephantsql.com/dwqawyqa
